let mySprite = sprites.create(img`
        . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . f f e e e e f 2 f . . . . 
            . . f f e e e e f 2 2 2 f . . . 
            . . f e e e f f e e e e f . . . 
            . . f f f f e e 2 2 2 2 e f . . 
            . . f e 2 2 2 f f f f e 2 f . . 
            . f f f f f f f e e e f f f . . 
            . f f e 4 4 e b f 4 4 e e f . . 
            . f e e 4 d 4 1 f d d e f . . . 
            . . f e e e e e d d d f . . . . 
            . . . . f 4 d d e 4 e f . . . . 
            . . . . f e d d e 2 2 f . . . . 
            . . . f f f e e f 5 5 f f . . . 
            . . . f f f f f f f f f f . . . 
            . . . . f f . . . f f f . . . .
    `, SpriteKind.Player)
scene.setBackgroundImage(img`
    .......................................................................e....................ee..........eeeee..............eeee.................................
        ...............................................e..........e...........e.ee.................e..e.......ee.....e.........eeee...e.................................
        .........e....ee.....................ee.......ee.........e.e........ee....e..............ee....eeeeeee........eeeeeeeee........e................................
        ..ee....eee...ee........e...........eee......e..e......ee...e.....ee.......ee..........ee.......................................eee.............................
        .eee...ee..eee..e......e.e........ee...e....e....e....e......eeeee...........eeeeeeeeee............................................eeeeeeeeeeeeeeee.............
        .e..eee..........e....e...e.....ee......eeeee.....eeee.............................................................................................e............
        ee................eeee.....eeeee....................................................................................................................eeeeeeeeeee.
        ................................................................................................................................................................
`)
tiles.setTilemap(tilemap`
    level1
`)
scene.cameraFollowSprite(mySprite)
scroller.scrollBackgroundWithCamera(scroller.CameraScrollMode.OnlyHorizontal)
controller.moveSprite(mySprite)
info.setScore(0)
info.setLife(3)
class Enemigo {
    en: Sprite
    constructor(): Enemigo {
        this.en = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
        `, SpriteKind.Enemy)
        this.en.setPosition(5, 5)
    }
    
}

let enemigo1 = new Enemigo()
